# name: Build and Deploy to Firebase
# on:
#   push:
#     branches:
#       - main
#       - master

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     environment: live
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#           cache: 'yarn'

#       - name: Install Dependencies
#         run: yarn install

#       # - name: Create .env file
#       #   run: |
#       #     echo "GATSBY_FIREBASE_API_KEY=${{ secrets.GATSBY_FIREBASE_API_KEY }}" >> .env
#       #     echo "GATSBY_FIREBASE_AUTH_DOMAIN=${{ secrets.GATSBY_FIREBASE_AUTH_DOMAIN }}" >> .env
#       #     echo "GATSBY_FIREBASE_PROJECT_ID=${{ secrets.GATSBY_FIREBASE_PROJECT_ID }}" >> .env
#       #     echo "GATSBY_FIREBASE_STORAGE_BUCKET=${{ secrets.GATSBY_FIREBASE_STORAGE_BUCKET }}" >> .env
#       #     echo "GATSBY_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.GATSBY_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
#       #     echo "GATSBY_FIREBASE_APP_ID=${{ secrets.GATSBY_FIREBASE_APP_ID }}" >> .env
#       #     echo "GATSBY_FIREBASE_MEASUREMENT_ID=${{ secrets.GATSBY_FIREBASE_MEASUREMENT_ID }}" >> .env

#       - name: Build Gatsby Site
#         run: yarn build
#         # env:
#         #   GATSBY_FIREBASE_API_KEY: ${{ secrets.GATSBY_FIREBASE_API_KEY }}
#         #   GATSBY_FIREBASE_AUTH_DOMAIN: ${{ secrets.GATSBY_FIREBASE_AUTH_DOMAIN }}
#         #   GATSBY_FIREBASE_PROJECT_ID: ${{ secrets.GATSBY_FIREBASE_PROJECT_ID }}
#         #   GATSBY_FIREBASE_STORAGE_BUCKET: ${{ secrets.GATSBY_FIREBASE_STORAGE_BUCKET }}
#         #   GATSBY_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.GATSBY_FIREBASE_MESSAGING_SENDER_ID }}
#         #   GATSBY_FIREBASE_APP_ID: ${{ secrets.GATSBY_FIREBASE_APP_ID }}
#         #   GATSBY_FIREBASE_MEASUREMENT_ID: ${{ secrets.GATSBY_FIREBASE_MEASUREMENT_ID }}

#       - name: Deploy to Firebase
#         uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: '${{ secrets.GITHUB_TOKEN }}'
#           firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
#           channelId: live
#           projectId: ${{ vars.FIREBASE_PROJECT_ID }}
